name: Hourly subreddit subscriber logger

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour (UTC)
  workflow_dispatch: {}

jobs:
  update-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw

      - name: Run PRAW script to fetch subscribers
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python praw_subs.py

      - name: Commit & push data.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update subscriber log: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi
